language: ruby

os: linux
dist: focal

rvm:
  - 3.3.4

addons:
  apt:
    packages:
      - cmake

before_install:
  - gem install bundler

install:
  - bundle install

before_script:
  - git clone https://github.com/CastXML/CastXML.git
  - mkdir CastXMLBuild
  - cd CastXMLBuild
  - cmake ../CastXML
  - make
  - export PATH=$PWD/bin:$PATH
  - cd ..

script:
  - bundle exec rspec

cache:
  bundler: true
  directories:
    - CastXMLBuild