name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cmake llvm-15 llvm-15-dev libclang-15-dev castxml
          version: 1.0

      - name: Install Ruby dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

      - name: Lint code for consistent style
        run: bundle exec rubocop --parallel